query GetPools {
  pools {
    token0 {
      name
      decimals
      symbol
      id
    }

    token1 {
      name
      decimals
      symbol
      id
    }

    feesUSD

    feeTier
    id
  }
}
